"""Add original_filename and media_type to media table

Revision ID: 28906580a69f
Revises: 3955e136d422
Create Date: 2025-06-07 15:29:34.159157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28906580a69f'
down_revision = '3955e136d422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'VICTIM'"))
        batch_op.alter_column('verification_status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('user_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False,
               existing_server_default=sa.text("'VICTIM'"))

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
