"""Add _bio column to users

Revision ID: 2930b0dfed90
Revises: f8ddc5456e07
Create Date: 2025-06-08 20:56:57.881396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2930b0dfed90'
down_revision = 'f8ddc5456e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_bio', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('_supporter_id_proof', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_supporter_id_proof')
        batch_op.drop_column('_bio')

    # ### end Alembic commands ###
