"""Add Media model

Revision ID: 3955e136d422
Revises: 3b48f848b381
Create Date: 2025-06-07 15:12:27.537973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3955e136d422'
down_revision = '3b48f848b381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='verificationstatusenum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='verificationstatusenum'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###
