"""Add user_type and supporter verification fields

Revision ID: 3b48f848b381
Revises: a6e7414bad7a
Create Date: 2025-06-07 07:26:46.847666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b48f848b381'
down_revision = 'a6e7414bad7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'user_type',
                sa.Enum('VICTIM', 'SUPPORTER', name='usertypeenum'),
                nullable=False,
                server_default='VICTIM'  # default value to avoid NOT NULL issues
            )
        )
        batch_op.add_column(sa.Column('is_verified_supporter', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('supporter_id_proof', sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column(
                'verification_status',
                sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatusenum'),
                nullable=True
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_status')
        batch_op.drop_column('supporter_id_proof')
        batch_op.drop_column('is_verified_supporter')
        batch_op.drop_column('user_type')
    # ### end Alembic commands ###