"""Add trust_points column to users

Revision ID: 3c8f9f589a33
Revises: 28906580a69f
Create Date: 2025-06-07 16:42:53.579893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8f9f589a33'
down_revision = '28906580a69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trust_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('negative_marks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('negative_marks')
        batch_op.drop_column('verified')
        batch_op.drop_column('trust_points')

    # ### end Alembic commands ###
