"""Updated User model cleanup

Revision ID: 45dc6dfaa041
Revises: cd4c40b58ad8
Create Date: 2025-06-08 02:36:52.003285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45dc6dfaa041'
down_revision = 'cd4c40b58ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('community_votes')
        batch_op.drop_column('proof_uploads')
        batch_op.drop_column('total_checkins')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_checkins', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('proof_uploads', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('community_votes', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
