"""Add trusted column to User

Revision ID: 588832579bcf
Revises: f8ef57b9a486
Create Date: 2025-06-07 05:00:15.953481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588832579bcf'
down_revision = 'f8ef57b9a486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trusted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('proof_file', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('proof_file')
        batch_op.drop_column('trusted')

    # ### end Alembic commands ###
