"""Add negative_action_count and warnings_count to User

Revision ID: a6e7414bad7a
Revises: 588832579bcf
Create Date: 2025-06-07 06:04:55.586198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e7414bad7a'
down_revision = '588832579bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('negative_action_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('warnings_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('warnings_count')
        batch_op.drop_column('negative_action_count')

    # ### end Alembic commands ###
